# Generated by Django 5.2 on 2025-05-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='document',
            new_name='linked_document',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='subscription',
            new_name='linked_subscription',
        ),
    ]
